# Generated by Django 5.1.1 on 2024-09-26 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0002_pdfdocument"),
    ]

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("content", models.TextField()),
                (
                    "photo",
                    models.ImageField(blank=True, null=True, upload_to="photos/"),
                ),
            ],
        ),
    ]
