# Generated by Django 5.1.1 on 2024-09-26 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='published_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
