# Generated by Django 5.1.1 on 2024-09-28 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0004_post_published_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="Phone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phone", models.CharField(max_length=255)),
            ],
            options={
                "verbose_name": "Телефон",
                "verbose_name_plural": "Телефон",
            },
        ),
        migrations.AlterModelOptions(
            name="customuser",
            options={
                "verbose_name": "Организации",
                "verbose_name_plural": "Организации",
            },
        ),
        migrations.AlterModelOptions(
            name="pdfdocument",
            options={"verbose_name": "ПВР и ППБ", "verbose_name_plural": "ПВР и ППБ"},
        ),
        migrations.AlterModelOptions(
            name="post",
            options={
                "verbose_name": "Календарь мероприятий",
                "verbose_name_plural": "Календарь мероприятий",
            },
        ),
    ]
