# Generated by Django 5.1.1 on 2024-09-28 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0005_phone_alter_customuser_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="phone",
            name="phone_displayed",
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
