# Generated by Django 5.1.1 on 2024-10-02 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_pages'),
    ]

    operations = [
        migrations.AddField(
            model_name='pages',
            name='page',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
