# Generated by Django 5.0.4 on 2025-04-03 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0008_pages_page"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="phone",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
