# Generated by Django 5.0.4 on 2025-04-04 07:30

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0009_customuser_email_customuser_phone"),
    ]

    operations = [
        migrations.DeleteModel(
            name="PDFDocument",
        ),
        migrations.DeleteModel(
            name="Phone",
        ),
        migrations.DeleteModel(
            name="Post",
        ),
        migrations.AlterField(
            model_name="pages",
            name="content",
            field=ckeditor.fields.RichTextField(),
        ),
    ]
