# Generated by Django 5.0.4 on 2025-04-04 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0010_delete_pdfdocument_delete_phone_delete_post_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pages",
            name="title",
        ),
    ]
